# Generated by Django 4.0.3 on 2022-03-24 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='co2',
            options={'ordering': ('date',)},
        ),
    ]
