apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      containers:
        - image: dan1ar/info-stambul-ui:latest
          name: app
          env:
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: info-secret
                  key: MINIO_ENDPOINT
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: info-secret
                  key: ACCESS_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: info-secret
                  key: SECRET_KEY
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              memory: "2Gi"
              cpu: "500m"

        - image: dan1ar/django-proxy:latest
          name: proxy
          ports:
            - containerPort: 8000
              name: proxy
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: '8080'

---

apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - port: 8000
  selector:
    app: django
    tier: app
  type: LoadBalancer
